"""added file_path and bot_response_file_path

Revision ID: 0333b634130a
Revises: 181dc78a1a0b
Create Date: 2026-07-18 02:42:19.327902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0333b634130a'
down_revision: Union[str, Sequence[str], None] = '181dc78a1a0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatconversation', sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('chatconversation', sa.Column('bot_response_file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatconversation', 'bot_response_file_path')
    op.drop_column('chatconversation', 'file_path')
    # ### end Alembic commands ###
