"""add user_message, bot_response columns

Revision ID: 181dc78a1a0b
Revises: 
Create Date: 2026-07-18 01:08:52.238541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # <- add this line
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '181dc78a1a0b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatwindow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chatconversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('bot_response', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chat_window_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_window_id'], ['chatwindow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chatconversation')
    op.drop_table('chatwindow')
    # ### end Alembic commands ###
